server:
  port: 8086


spring:
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8089
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dilect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-Url:
#      defaultZone: http://localhost:8761/eureka

okta:
  oauth2:
    issuer: https://dev-64205235.okta.com/oauth2/default
    audience: api://default
