server:
  port: 8089

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AdarshKing56/microservice-configuration-server
          clone-on-start: true


